[package]
name = "crabbymetrics"
version = "0.2.1"
edition = "2021"

[lib]
name = "crabbymetrics"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
numpy = "0.27"
ndarray = "=0.16.1"
linfa = "0.8.1"
linfa-linear = "0.8.1"
linfa-logistic = "0.8.1"
linfa-elasticnet = "0.8.1"
linfa-ftrl = "0.8.1"
rand = "0.8"
nalgebra = "0.33"
argmin = "0.11"
argmin-math = "0.5"
within = "0.1.0"
